### PR TITLE
Fixed issues with filenames

### PR DESCRIPTION
**Pull request by raspyrandom**
Fixed issues with filenames

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Appears functional -- Please don't leave "Easter egg" comments in the future. This is a serious project.

**Review by ghost — APPROVED** [review]
Appears functional -- Please don't leave "Easter egg" comments in the future. This is a serious project.

**Review by ghost — CHANGES_REQUESTED** [review]
test

**Review by nilederg — APPROVED** [review]
Good changes. Thanks for the proactive insights.

**Pull request merged**
